apiVersion: v1
kind: Pod
metadata:
  name: test1
  namespace: default
spec:
  containers:
    - env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: db-user
              name: test-secret
        - name: DB_PWD
          valueFrom:
            secretKeyRef:
              key: db-password
              name: test-secret
        - name: GAUSS
          value: a
        - name: OPEN
          value: b
        - name: LOOK
          value: c
        - name: MIND
          value: d
      image: ccr.ccs.tencentyun.com/kugo/demo:v6
      imagePullPolicy: IfNotPresent
      name: test-k8s
      volumeMounts:
        - mountPath: /opt/demo/config
          name: app-config
      args:
        - --config-file=/opt/demo/config/config.yaml
  volumes:
    - name: app-config
      configMap:
        name: test-config