port: 8000

log:
  level: INFO
  filename: logs/go-web

mysql:
  db_host: ${DB_HOST}
  db_port: 3306
  db_user: "root"
  db_pwd: "12345678"
  db_name: "cves_go"
  db_max_conn: 20
  db_maxidle: 100
  table:
    compatibility_osv: oe_compatibility_osv

es:
  host: "http://localhost"
  port: 9200
  indexs:
    pull_index: "pr_index"

redis:
  host: ${DB_HOST}
  port: 6379

mongo:
  host: ${DB_HOST}
  port: 27017
  database: "mydb"
  collection: "dd"

postgresql:
  db_host: "49.0.247.41"
  db_port: 30051
  db_user: "cve-manager"
  db_pwd: "BW2Rynr!LKWwjA2s"
  db_name: "cve-manager"
  db_max_conn: 500
  db_maxidle: 1000
  table:
    cve_basic_info_test: cve_basic_info_test

etcd:
  host: ${DB_HOST}
  port: 2379

kafka:
  host: ${DB_HOST}
  port: 9092

kubernetes:
  pod:
    image: "ccr.ccs.tencentyun.com/kugo/demo:v6"
    secret: "test-secret"
    name: test
    args:
      - --config-file=/opt/demo/config/config.yaml
    port: 8080
  namespace: "default"
  config_map:
    config_map_name: "test-config"
    config_name: "app-config"
    mounth_path: "/opt/demo/config"
  crd:
    group: code.zjm.com
    version: v1
    kind: CodeServer