port: 8000

log:
  level: INFO
  filename: logs/go-web

mysql:
  db_host: ${DB_HOST}
  db_port: 3306
  db_user: "root"
  db_pwd: "12345678"
  db_name: "cves_go"
  db_max_conn: 20
  db_maxidle: 100
  table:
    compatibility_osv: oe_compatibility_osv

es:
  host: "http://localhost"
  port: 9200
  indexs:
    pull_index: "pr_index"

redis:
  host: ${DB_HOST}
  port: 6379

mongo:
  host: ${DB_HOST}
  port: 27017
  database: "mydb"
  collection: "dd"

postgres:
  db_host: "192.168.1.218"
  db_port: 5432
  db_user: "postgres"
  db_pwd: "root"
  db_name: "cve-manager"
  db_max_conn: 500
  db_maxidle: 1000
  table:
    basic_info: basic_info
    community_pkg: community_pkg

etcd:
  host: ${DB_HOST}
  port: 2379

kafka:
  host: ${DB_HOST}
  port: 9092

kubernetes:
  pod:
    image: "ccr.ccs.tencentyun.com/kugo/demo:v6"
    secret: "test-secret"
    name: test
    args:
      - --config-file=/opt/demo/config/config.yaml
    port: 8080
  namespace: "default"
  config_map:
    config_map_name: "test-config"
    config_name: "app-config"
    mounth_path: "/opt/demo/config"
  crd:
    group: code.zjm.com
    version: v1
    kind: CodeServer
task:
  pkg:
    exec: "20 40 15 * * *"
    packages:
      - community: opengauss
        type: "application"
        org: opengauss
        platform: gitee
        url:
#          - https://gitee.com/opengauss/openGauss-tools-sql-translator/raw/master/Third_Party_Open_Source_Software_List.yaml
          - https://gitee.com/opengauss/openGauss-connector-jdbc/raw/master/Third_Party_Open_Source_Software_List.yaml
#          - https://gitee.com/opengauss/DataStudio/raw/master/Third_Party_Open_Source_Software_List.yaml
          - https://gitee.com/opengauss/openGauss-third_party/raw/master/Third_Party_Open_Source_Software_List.yaml
      - community: mindspore
        type: "application"
        org: mindspore
        platform: gitee
        url:
          - https://gitee.com/mindspore/community/raw/master/security/config/Third_Party_Open_Source_Software_List.yaml
#      - community: openlookeng
#        type: "application"
#        org: openlookeng
#        platform: gitee
#        url:
#          - https://gitee.com/openlookeng/community/raw/master/security/config/Third_Party_Open_Source_Software_List.yaml
#      - community: openeuler
#        type: "base"
#        org: src-openeuler
#        platform: gitee
#        url:
#          - http://omapi.osinfra.cn/v1/versions?community=openeuler