port: 8000

log:
  level: INFO
  filename: logs/go-web

mysql:
  db_host: ${DB_HOST}
  db_port: 3306
  db_user: "root"
  db_pwd: "12345678"
  db_name: "cve"
  db_max_conn: 20
  db_maxidle: 100

es:
  host: "http://localhost"
  port: 9200

redis:
  host: ${DB_HOST}
  port: 6379

mongo:
  host: ${DB_HOST}
  port: 27017
  database: "mydb"
  collection: "dd"

postgresql:
  db_host: ${DB_HOST}
  db_port: 5432
  db_user: "postgres"
  db_pwd: "root"
  db_name: "postgres"
  db_max_conn: 20
  db_maxidle: 100

etcd:
  host: ${DB_HOST}
  port: 2379

kubernetes:
  pod:
    image: "ccr.ccs.tencentyun.com/kugo/demo:v6"
    secret: "test-secret"
  namespace: "default"
  config_map:
    config_map_name: "test-config"
    config_name: "app-config"
    mounth_path: "/opt/demo/config"
  crd:
    group: code.zjm.com
    version: v1
    kind: CodeServer